name: FirstAction
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checout Repository
      uses: actions/checkout@v3
    - name: Setup .Net
      uses: actions/setup-dotnet@v3
      with:
        donet-version: '8.0.0'
    - name: Restore dependencies
      run: dotnet restore
    - name: Run tests
      run: dotnet test --logger trx
